apiVersion: apps/v1
kind: Deployment
metadata:
  name: selex
  labels:
    app: selex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selex
  template:
    metadata:
      labels:
        app: selex
    spec:
      containers:
      - name: selex
        image: selex:1.0
        ports:
          - containerPort: 8080
        env:
          - name: GRIDURI
            value: "http://selenium-hub:4444"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
            