apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:4.0.0
        env:
#          - name: GRID_TIMEOUT 
#            value: "30"
          - name: GRID_NEW_SESSION_WAIT_TIMEOUT
            value: "60"
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5