apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: selenium-node-firefox-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selenium-node-firefox
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: External
    external:
      metric:
        name: selenium_grid_hub_firefoxsessionsinusepercent
      target:
        type: Value
        value: 75