apiVersion: v1
kind: Service
metadata:
  name: selex
  labels:
    app: selex
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: port0
  selector:
    app: selex
  type: NodePort
  sessionAffinity: None