apiVersion: apps/v1
kind: Deployment
metadata:
  name: selvidere
  labels:
    app: selvidere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selvidere
  template:
    metadata:
      labels:
        app: selvidere
    spec:
      containers:
      - name: selvidere
        image: selvidere:1.0
        env:
          - name: GRIDURI
            value: "http://selenium-hub:4444"
          - name: INTERVAL
            value: "5"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
            
