apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: selenium-node-firefox-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.firefox.name }}"
  minReplicas: {{ .Values.firefox.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.firefox.autoscaling.maxReplicas }}
  metrics:
  - type: External
    external:
      metric:
        name: selenium_grid_hub_firefoxsessionsinusepercent
      target:
        type: Value
        value: {{ .Values.firefox.autoscaling.targetValue }}