apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.hub.name }}"
  labels:
    app: "{{ .Values.hub.name }}"
spec:
  replicas: {{ .Values.hub.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.hub.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.hub.name }}"
    spec:
      containers:
      - name: "{{ .Values.hub.name }}"
        image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.hub.image.pullPolicy }}"
        env:
          - name: GRID_NEW_SESSION_WAIT_TIMEOUT
            value: "{{ .Values.hub.env.gridNewSessionWaitTimeout }}"
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5