apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.hub.name }}"
  labels:
    app: "{{ .Values.hub.name }}"
spec:
  type: {{ .Values.hub.service.type }}
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: {{ .Values.hub.service.nodePort }}
    name: port0
  - port: 4442
    targetPort: 4442
    name: port1
  - port: 4443
    targetPort: 4443
    name: port2
  selector:
    app: "{{ .Values.hub.name }}"
  sessionAffinity: None