apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.selex.name }}"
  labels:
    app: "{{ .Values.selex.name }}"
spec:
  replicas: {{ .Values.selex.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.selex.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.selex.name }}"
    spec:
      containers:
      - name: selex
        image: "{{ .Values.selex.image.repository }}:{{ .Values.selex.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: 8080
        env:
          - name: GRIDURI
            value: "http://{{ .Values.hub.name }}:{{ .Values.hub.service.port }}"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
            