apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.selex.name }}"
  labels:
    app: "{{ .Values.selex.name }}"
spec:
  type: {{ .Values.selex.service.type }}
  ports:
  - port: {{ .Values.selex.service.port }}
    targetPort: {{ .Values.selex.service.port }}
    nodePort: {{ .Values.selex.service.nodePort }}
    name: port0
  selector:
    app: "{{ .Values.selex.name }}"
  sessionAffinity: None