apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.selvidere.name }}"
  labels:
    app: "{{ .Values.selvidere.name }}"
spec:
  replicas: {{ .Values.selvidere.replicaCount }}
  selector:
    matchLabels:
      app: selvidere
  template:
    metadata:
      labels:
        app: selvidere
    spec:
      containers:
      - name: selvidere
        image: "{{ .Values.selvidere.image.repository }}:{{ .Values.selvidere.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: 8080
        env:
          - name: GRIDURI
            value: "http://{{ .Values.hub.name }}:{{ .Values.hub.service.port }}"
          - name: INTERVAL
            value: "{{ .Values.selvidere.interval }}"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
            